// record-tests.js

/**
 * Launches the Playwright Codegen tool for manual test recording.
 *
 * It uses the 'storageState.json' file generated by the 
 * 'playwright.config.js' globalSetup to start the recording session
 * in an already authenticated state.
 */
const { execSync } = require('child_process');
const path = require('path');

const BASE_URL = process.argv[2] || 'http://localhost:3000';
const STORAGE_STATE_PATH = path.join(process.cwd(), 'storageState.json');
const OUTPUT_FILE = process.argv[3] || 'tests-playwright/recorded-test.spec.js';

console.log(`\n\x1b[34m--- Playwright Codegen Recorder ---\x1b[0m`);
console.log(`\x1b[33mBase URL:\x1b[0m ${BASE_URL}`);
console.log(`\x1b[33mOutput File:\x1b[0m ${OUTPUT_FILE}`);
console.log(`\x1b[32mLaunching browser in authenticated mode...\x1b[0m`);

try {
    // Construct the command to run Playwright Codegen
    const command = [
        'npx playwright codegen',
        BASE_URL,
        `--save-storage=${STORAGE_STATE_PATH}`, // Ensures we don't overwrite the auth file if recording logs out
        `--load-storage=${STORAGE_STATE_PATH}`, // Loads the authenticated state
        `--output=${OUTPUT_FILE}`, // Sets the output file
        '--browser=chromium', // Specify a browser
        '--verbose'
    ].join(' ');

    // Execute the command synchronously
    execSync(command, { stdio: 'inherit' });

    console.log(`\n\x1b[32mRecording finished. Test saved to ${OUTPUT_FILE}\x1b[0m`);

} catch (error) {
    console.error(`\n\x1b[31mError running Playwright Codegen:\x1b[0m`, error.message);
    console.log(`\n\x1b[33mMake sure Playwright is installed: npm install -D playwright\x1b[0m`);
}
